include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    - always_put_required_named_parameters_first
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_classes_with_only_static_members
    - avoid_dynamic_calls
    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_returning_null_for_future
    - avoid_void_async
    - avoid_web_libraries_in_flutter
    - cascade_invocations
    - lines_longer_than_80_chars
    - cancel_subscriptions
    - constant_identifier_names
    - deprecated_consistency
    - directives_ordering
    - eol_at_end_of_file
    - flutter_style_todos
    - no_default_cases
    - no_leading_underscores_for_library_prefixes
    - no_leading_underscores_for_local_identifiers
    - noop_primitive_operations
    - omit_local_variable_types
    - only_throw_errors
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_null_aware_method_calls
    - prefer_single_quotes
    - prefer_void_to_null
    - require_trailing_commas
    - secure_pubspec_urls
    - sized_box_shrink_expand
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_constructor_name
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_statements
    - use_build_context_synchronously
    - use_decorated_box
    - use_if_null_to_convert_nulls_to_bools
    - use_late_for_private_fields_and_variables
    - use_setters_to_change_properties
    - use_test_throws_matchers
    - use_to_and_as_if_applicable

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-arguments: 4
  metrics-exclude:
    - test/**
  rules:
    - always-remove-listener
    - avoid-border-all
    - avoid-collection-methods-with-unrelated-types
    - avoid-global-state
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions:
        acceptable-level: 2
    - avoid-returning-widgets
    - avoid-throw-in-catch-block
    - avoid-unnecessary-setstate
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-wrapping-in-padding
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
  # - member-ordering-extended
    - newline-before-return
    - no-boolean-literal-compare
    - no-equal-then-else
  # - no-magic-number
    - prefer-conditional-expressions
  # - prefer-extracting-callbacks
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    - prefer-match-file-name:
        exclude:
          - test/**
  # - prefer-moving-to-variable
    - prefer-trailing-comma
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
  anti-patterns:
    - long-parameter-list

analyzer:
  plugins:
    - dart_code_metrics

  errors:
    always_put_required_named_parameters_first: ignore
    always_use_package_imports: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    implicit_dynamic_list_literal: ignore
    implicit_dynamic_map_literal: ignore
    implicit_dynamic_parameter: ignore
    implicit_dynamic_variable: ignore
    library_private_types_in_public_api: ignore
    prefer_asserts_with_message: ignore
    prefer_int_literals: ignore
    public_member_api_docs: ignore
    sort_constructors_first: ignore
    unused_element: ignore
