name: cabin_booking
description: An app for booking cabins.
version: 0.5.0
publish_to: none

repository: https://github.com/albertms10/cabin_booking.git

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.16.0
  cupertino_icons: ^1.0.4
  fl_chart: ^0.50.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  horizontal_data_table: ^3.6.3
  intl: ^0.17.0
  nanoid: ^1.0.0
  path_provider: ^2.0.10
  provider: ^6.0.2
  timer_builder: ^2.0.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  dart_code_metrics: ^4.15.1
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
