name: cabin_booking
description: An app for booking cabins.
version: 0.4.0
publish_to: none

author: Albert Mañosa <albertmasa2@gmail.com>
repository: https://github.com/albertms10/cabin_booking.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  horizontal_data_table: ^3.4.3
  intl: any
  path_provider: ^2.0.3
  provider: ^6.0.0
  timer_builder: ^2.0.0
  uuid: ^3.0.4
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter:
  generate: true
  uses-material-design: true
