name: cabin_booking
description: An app for booking cabins.
version: 0.4.0
publish_to: none

repository: https://github.com/albertms10/cabin_booking.git

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  collection: ^1.15.0
  cupertino_icons: ^1.0.3
  fl_chart: ^0.40.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  horizontal_data_table: ^3.5.0
  intl: any
  path_provider: ^2.0.5
  provider: ^6.0.1
  timer_builder: ^2.0.0
  uuid: ^3.0.5
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  dart_code_metrics: ^4.4.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.3.0

flutter:
  generate: true
  uses-material-design: true
