name: Analysis CI

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/dependabot.yaml"
      - ".github/workflows/build-cd.yaml"
      - ".github/workflows/scorecards-analysis.yaml"
      - ".vscode/**"
      - "android/**"
      - "docs/**"
      - "ios/**"
      - "macos/**"
      - "windows/**"
      - "**.md"
      - ".gitattributes"
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENSE"

  pull_request:
    branches: [main]
    types: [opened, synchronize, ready_for_review, reopened]
    paths-ignore:
      - ".github/dependabot.yaml"
      - ".github/workflows/build-cd.yaml"
      - ".github/workflows/scorecards-analysis.yaml"
      - ".vscode/**"
      - "android/**"
      - "docs/**"
      - "ios/**"
      - "macos/**"
      - "windows/**"
      - "**.md"
      - ".gitattributes"
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENSE"

  release:
    types: [published]

env:
  FLUTTER_SDK_VERSION: "3.7.0"

permissions:
  contents: read

jobs:
  analyze:
    permissions:
      checks: write # for coverallsapp/github-action to create new checks
      contents: read # for actions/checkout to fetch code
    name: Analyze
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@b56e6a3d768b11aef1d4c73977caf6413c0d74c8 # v3

      - name: Cache dependencies
        uses: actions/cache@6998d139ddd3e68c71e9e398d8e40b71a2f39812 # v3.2.5
        id: cache
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-pubspec-${{ env.FLUTTER_SDK_VERSION }}-${{ hashFiles('**/pubspec.lock') }}

      - uses: subosito/flutter-action@dbf1fa04f4d2e52c33185153d06cdb5443aa189d # v2.8.0
        with:
          flutter-version: ${{ env.FLUTTER_SDK_VERSION }}

      - name: Verify formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Get dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --no-pub --fatal-infos

      - name: Analyze Dart Code Metrics
        run: flutter pub run dart_code_metrics:metrics analyze lib --fatal-style --fatal-performance

      - name: Run tests
        run: flutter test test/main.dart --no-pub --coverage

      - name: Upload Coveralls
        uses: coverallsapp/github-action@9ba913c152ae4be1327bfb9085dc806cedb44057 # 1.1.3
        continue-on-error: true
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
